2017-06-17 09:42:14,440 [1] ERROR GuardTourSystem.App - 未将对象引用设置到对象的实例。
 GuardTourSystem.AppnameSystem.NullReferenceException: 未将对象引用设置到对象的实例。
   在 GuardTourSystem.Utils.InputChecker.CheckRfidCard(String& card, Int32 length) 位置 d:\WindowsProjects\GuardTourSystem(4位卡号-计数管理系统)\GuardTourSystemV2.0.1\GuardTourSystem4位卡号\Utils\InputChecker.cs:行号 15
   在 GuardTourSystem.Model.Place.set_EmployeeNumber(String value) 位置 d:\WindowsProjects\GuardTourSystem(4位卡号-计数管理系统)\GuardTourSystemV2.0.1\GuardTourSystem4位卡号\Database\Model\Place.cs:行号 65
   在 GuardTourSystem.ViewModel.RoutePlaceViewModel.OnBatchAdd(List`1 selectItems) 位置 d:\WindowsProjects\GuardTourSystem(4位卡号-计数管理系统)\GuardTourSystemV2.0.1\GuardTourSystem4位卡号\ViewModel\PatrolSetting\RouteSettings\RoutePlaceViewModel.cs:行号 476
   在 GuardTourSystem.ViewModel.BatchAddViewModel.BatchAdd() 位置 d:\WindowsProjects\GuardTourSystem(4位卡号-计数管理系统)\GuardTourSystemV2.0.1\GuardTourSystem4位卡号\ViewModel\Custom\BatchAddViewModel.cs:行号 271
   在 Microsoft.Practices.Prism.Commands.DelegateCommandBase.<>c__DisplayClass2.<.ctor>b__0(Object arg)
   在 Microsoft.Practices.Prism.Commands.DelegateCommandBase.<Execute>d__7.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.Practices.Prism.Commands.DelegateCommandBase.<System.Windows.Input.ICommand.Execute>d__4.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
